services:
  nginx:
    image: nginx:latest
    ports:
      - "5174:5174"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data:/data